### ISSUE TITLE
locale file in src folder

### ISSUE THREAD

**Issue by akashpatni** [legios89/django-docker-bootstrap#43]
Hi,
I am not able to create locale folder in src directory as I need to do some changes in locale file. Can you please tell me how locale file for particular language can be created.
I am using following command in django shell for generating it with no success

django-admin makemessages -l zh-hans

Please help
Thanks

**Comment by legios89** [comment]
I think that you did everything fine, but there is a trick in here.
First, you need the enter a django container: `dc run --rm django shell`, and inside the container you can create the translations with the ``django-admin makemessages -l zh-hans` command.

Second, the locale files are stored inside the base(data) container.
If you check the following file: [makemessages.py](https://github.com/legios89/django-docker-bootstrap/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/src/core/management/commands/makemessages.py)

You can see that after the translations are created. I move them to the /data/ folder.
The main reason why I did this because I want to store the data, and code separately, and in my view the translations are data.

I hope that this will help you! :)

**Comment by akashpatni** [comment]
Hi,

Thank you for the update.

In my setup no data folder is created and when I am running the project it is giving permission denied error for data folder.
But I can see that one locale file is created in the image itself but I can not access that file as it is in image and I want to make changes in locale file. So for now I have commented the one line from makemessages.py which is moving file from src to data.

Please help.

**Comment by legios89** [comment]
You should try to modify it inside a running container with vim. I think that the reason why you received `permission denied`, that you tried to access it outside of a container.
I store every data here(database files, static files, media, translations) to make the backup creation easier. The data folder automatically created you can find it if you start any container in the:
/data/

If you want to store the locale files in the src folder, then you should delete the `makemessages.py` completely , plus you need the change the LOCALE_PATHS to following in the settings.py: 
`LOCALE_PATHS = ('/src/locale/',)`

**Comment by akashpatni** [comment]
Thanks for the help!

One more query regarding images.

I am able to run the project on my ubuntu system but when I am running the same system on windows it is giving error-
**python3: can't open file'/config/run.py': [Errno 2] No such file or directory** 
Also I have push the images on docker hub and using the same image to run the project but with no success.
I have tried both the methods that is by building new image on windows and by pulling image from docker hub but it is giving error

Please help

**Comment by legios89** [comment]
To be honest, I never tested this on windows, but I have some idea about what you can do to determine the problem.

First if you check this file: [docker-compose.py](https://github.com/legios89/django-docker-bootstrap/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/docker-compose.yml)
You can see that every container have the followings:
-  `entrypoint: ['python3', '/config/run.py']`
- `command: start`

So when the docker compose try to start the project, the first command will be this `python3 /config/run.py start`.

You should replace the entry point with this: `/bin/bash` and after you entered the container check the file because it should be there.
