### ISSUE TITLE
How to run cron using Django Package CRONTAB 

### ISSUE THREAD

**Issue by akashpatni** [legios89/django-docker-bootstrap#44]
Hi All,

I am using the django-docker-bootstrap in my project and its need to run cron job and for that I have installed the django package CronTab. And I have define one function for that by using the below URL. Now I am running command djano-admin crontab add and it is giving erorr:

sh: 1: /usr/bin/crontab: not found
 Can any one please tell me how to add cron job into crontab.

I have installed the CRONTAB using the below link:
https://pypi.python.org/pypi/django-crontab

Thanks in advance

**Comment by legios89** [comment]
You need to create a new docker service in the docker-compose.yml.
The problem is that one docker container can't run multiple task.
So by default, there is no cron service inside a docker container.

For example, the django service starts the Django server and that's all.
You need to create a new service which is work like the django, but replace the start command with this: `python manage.py crontab add`

After this, it should work, but I never tried this before.

**Comment by akashpatni** [comment]
Hi,

I have tried the method as per your suggestion but its not getting worked.
can you please help me on making cron service like django in docker-compose.yml

Thanks

**Comment by akashpatni** [comment]
Hi,

I want to set CRON using UNIX cron tab for that I need project directory, but when I am entering in container Proxy using docker exec -t -i 66175bfd6ae6 bash command I am not able to locate project directory.I want to set cron using below command

> crontab -e

*/5 \* \* \* \* source /home/ubuntu/.bashrc && source /home/ubuntu/work/your-project/bin/activate && python /home/ubuntu/work/your-project/src/manage.py runcrons > /home/ubuntu/cronjob.log

useful link: http://django-cron.readthedocs.io/en/latest/installation.html

Please help me on that.

**Comment by legios89** [comment]
Hi!
Maybe the followings will help you.
- I don't think that you need  add this to the crontab:  `source /home/ubuntu/.bashrc && source /home/ubuntu/work/your-project/bin/activate`
  Because you only need this if you use a virtual environment.
  http://docs.python-guide.org/en/latest/dev/virtualenvs/
- The project folder can be found inside the django container in here: `/src/`
- You should redirect the log to `/data/logs/conjob.log`, because by default the project store every logs there.

So you should use the following command:
`docker exec django python /src/manage.py > /data/logs/cronjob.log`
